### ISSUE TITLE
Trial Design Tool creates unusable designs

### ISSUE THREAD

**Issue by dwaring87** [solgenomics/sgn#3673] opened 2021-08-23 14:33 UTC
Expected Behavior 
--------------------------------------------------------------------------

When designing an RCBD trial with the plot number starting with 1, the trial design tool creates trials with missing plots/accessions and gaps between plots:

![image](https://user-images.githubusercontent.com/7526014/130465228-57074a79-437a-4620-8d15-c9ad86cb570d.png)

All but the last block are capped to 10 plots/accessions (each block should have 15).

![image](https://user-images.githubusercontent.com/7526014/130465417-6bbb9917-8315-4c58-b945-b83462cd1fc2.png)

----

The tool works correctly when the plot number starts with 101:

![image](https://user-images.githubusercontent.com/7526014/130465541-da2b5cd4-bced-44d1-a3ad-6020eb9695c7.png)

![image](https://user-images.githubusercontent.com/7526014/130465597-300f9672-4b47-4a72-9e14-f6a6f7c09492.png)

For Bugs:
---------

**Comment by ch728** [comment] 2021-08-23 15:28
Seems like a duplicate of #3471 ?

**Closed** 2021-08-30 15:34 UTC
Labels: Priority: Critical
