### ISSUE TITLE
Mixed Model Tool Issues

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#3922] opened 2022-01-27 21:04 UTC
Started playing around with the mixed model tool a little. I noticed a couple of issues.

1. There is no way to specify a nesting of variables, only interaction. It is common to nest rep in location to make unique rep factor for example.
2.  After running a model the results are shown with no header for the traits (see below) and there is no way to download the result. 
![Screenshot from 2022-01-27 15-57-21](https://user-images.githubusercontent.com/36375878/151442531-662ed049-29ad-46e7-852f-758e07171c12.png)
3. The save button allows one to save the analysis in the database (models can be saved though); however, this doesn't seem to work yet as I get this error message when trying to save the analysis:
![Screenshot from 2022-01-27 16-01-03](https://user-images.githubusercontent.com/36375878/151443007-ad3a8c6c-56b4-4816-b964-fc959bcf4398.png)

I understand this is a newer tool and under active development, just wanted to provide some (hopefully) useful feedback!

**Comment by lukasmueller** [comment] 2022-01-28 20:00
Hi Chris, do you have a location called [Computation] in the database? That's what the tool uses as location. Sometimes users delete this location because they think it is not useful

**Comment by lukasmueller** [comment] 2022-01-28 20:00
There is a ticket for adding nested variables. I thought there was a download, if not we should definitely add that option and have proper headers.

**Comment by ch728** [comment] 2022-01-29 14:19
I definitely deleted the Computation location. Can I simply add a location called Computation to fix this?

**Comment by lukasmueller** [comment] 2022-01-29 21:04
Yes. It has to be called [Computation] (with the brackets)
Maybe we should change this or prevent it from getting deleted.
cheers
Lukas
________________________________

**Comment by lukasmueller** [comment] 2022-01-31 03:05
added issue #3927  to prevent computation location deletion. Pull request #3928.

**Comment by lukasmueller** [comment] 2022-01-31 03:06
Let's make this issue about adding a header and the download. (nesting already has an issue.)

**Comment by ch728** [comment] 2022-01-31 04:10
Okay, sounds good. I added the [Computation] location back and it fixed the issue with saving the analysis.

**Comment by lukasmueller** [comment] 2022-09-12 14:39
Closing this issue as a duplicate of #3997.

**Closed by lukasmueller** 2022-09-12 14:39 UTC
Labels: Type: Feature Request, Priority: High
