### ISSUE TITLE
Pedigree download on musabase gives a popup that accession list did not pass validation. However, the list passed validation within the list page.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#3865] opened 2021-12-03 17:19 UTC
Expected Behavior 
--------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/10618260/144644994-5eecb2b3-e039-4181-9bf7-21e7038f5a5f.png)

For Bugs:
---------

**Comment by wolfemd** [comment] 2021-12-05 15:24
I am encountering (and have recently reported) the exact same issue with Cassavabase. No feedback given in validation tool or otherwise as to the problem.

**Comment by lukasmueller** [comment] 2022-01-02 22:45
Is this still an issue? I think this was fixed via 4b9a9cd6ee888d9f6076d1dc7349b07070f1d156.

**Comment by wolfemd** [comment] 2022-01-03 12:56
Yes, it's still an issue. Just tried with the following public list "IITA_ExampleGSaccessions_2021Dec05" which passes validation in the main tool, but gives the "validation fail" error at pedigree download.

**Comment by lukasmueller** [comment] 2022-01-03 15:29
On my vm it works with my own lists, maybe the issue is public lists? Is that list your own list?

**Comment by wolfemd** [comment] 2022-01-03 15:34
It is my own list, which I made public so you could potentially use it to
find the problem.

**Comment by lukasmueller** [comment] 2022-01-03 15:51
OK, I see what's happening. There are some lines in the list that have their own uniquename also as a synonym, and this check doesn't seem to like that. However, I think this should be allowed, what do you think? It is not quite ok to have the same synonym as your own name, but it should not wreak havoc...

**Comment by wolfemd** [comment] 2022-01-03 16:14
I really don't know. Could having the uniquename also as a synonym be
prevented?
Either way, each breeding program needs to be responsible for the
representation and naming of their germplasm. Users like myself just need
to get whatever pedigree is available (if any) corresponding to a given,
validated list.

**Comment by lukasmueller** [comment] 2022-01-03 16:16
yes, I will fix that so that the pedigrees will download either way

**Comment by lukasmueller** [comment] 2022-01-04 21:12
there were some additional edge cases that the interactive list validator didn't catch, but the non-interactive did. It should catch them now so you should be able to see additional problems in your list. There is an entry that matches a synonym, and another entry that matches synonyms to two different stocks.

**Comment by lukasmueller** [comment] 2022-01-31 03:11
fixed via #3888.

**Closed by lukasmueller** 2022-01-31 03:11 UTC
Labels: Type: Bug, Priority: High
