### ISSUE TITLE
Dataset detail page and outlier filtering

### ISSUE THREAD

**Issue by ClayBirkett** [solgenomics/sgn#4116] opened 2022-06-06 15:33 UTC
Feature request
create a page to manage datasets
name, description, contents, delete, make public, make private
this feature would enable the addition of a description for datasets which could include a publication
another nice option would be ability to allow external link to a dataset detail page

**Comment by lukasmueller** [comment] 2022-09-20 18:47
The dataset introspection page also implements outlier filtering, as explained in #3800 .

**Comment by lukasmueller** [comment] 2022-09-20 18:48
Deleting #3800 as a duplicate of this ticket.

**Comment by lukasmueller** [comment] 2022-09-20 18:53
For a good description of the outlier filtering feature, see #3454 .

**Comment by lukasmueller** [comment] 2022-10-07 14:13
Closing this as a duplicate of #3454 and #3800.

**Closed by lukasmueller** 2022-10-07 14:13 UTC
Labels: Type: Feature Request
