### ISSUE TITLE
Editable stock properties don't work in advanced search

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#3653] opened 2021-08-12 00:02 UTC
I added some additional stock properties in  editable_stock_props in my sgn_local.conf. For example, herbicide_class and grain_class. These properties are loaded into the database for accessions and are available in the advanced search menu, but when I try to search I get this error message in the log:

021-08-12 00:00:54.404 UTC [137] ERROR:  column "grain_class" does not exist at character 51
breedbase_db    | 2021-08-12 00:00:54.404 UTC [137] STATEMENT:  SELECT stock_id FROM materialized_stockprop WHERE "grain_class"::text ilike '%Long%';
breedbase_web   | Stock search AJAX
breedbase_web   | CXGN::Stock::Search search start
breedbase_web   | [error] CXGN::Stock::Search::search(): DBI Exception: DBD::Pg::st execute failed: ERROR:  column "grain_class" does not exist
breedbase_web   | LINE 1: SELECT stock_id FROM materialized_stockprop WHERE "grain_cla...
breedbase_web   |                                                           ^ [for Statement "SELECT stock_id FROM materialized_stockprop WHERE "grain_class"::text ilike '%Long%';"] at lib/SGN/Controller/AJAX/Search/Stock.pm line 87

**Comment by lukasmueller** [comment] 2021-08-23 15:26
duplicate of #3284

**Closed** 2024-09-05 15:36 UTC
