### ISSUE TITLE
Can we associate stockprops to accessions on the pedigree viewer tool. 

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#1615] opened 2018-02-08 17:35 UTC
Expected Behavior 
--------------------------------------------------------------------------
It would be useful to show some stockprops for a particular accession on the pedigree Viewer. Example maybe year of development, ploidy_level, etc.

Requested by Agre. 

For Bugs:
---------

**Comment by bauchetg** [comment] 2018-02-21 11:31
Other good use cases would be populations, in case of very large set of progenies, hard to visualize, they could grouped by existing associated population, as here:
<img width="208" alt="screen shot 2018-02-21 at 2 28 01 pm" src="https://user-images.githubusercontent.com/12039071/36477906-d9f43740-1713-11e8-8eb0-daafdd5d3dbc.png">

**Comment by dauglyon** [comment] 2018-03-19 18:52
Because there is not currently a BrAPI call which will let us do this, I am going to close this issue. However, trait overlays (from observations) will be available. It may also be possible to add overlays which use other data returned in the germplasm object.

**Comment by dauglyon** [comment] 2018-03-22 15:40
We may be able to impliment this using [germplasm attributes](https://brapi.docs.apiary.io/#reference/germplasm/germplasm-markerprofiles/attributes-by-attributecategorydbid)

**Comment by dauglyon** [comment] 2018-03-22 16:08
Yes, it looks like I missed this the first go around. Germplasm Attributes should work to let us do this, it looks like our current BrAPI implementation is already giving some stockprops as attributes.

**Comment by dauglyon** [comment] 2019-04-04 20:13
This can be done using the changes in https://github.com/solgenomics/BrAPI-Pedigree-Viewer/commit/ae07ae28a5f0ab0a7efcfbe550071b783541d23d and is basically a duplicate of #1501 but covering different "traits"

**Closed by dauglyon** 2019-04-04 20:13 UTC
