### ISSUE TITLE
Synonyms uniquename stock conflict during trial creation. 

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#2151] opened 2018-09-07 12:37 UTC
Expected Behavior 
--------------------------------------------------------------------------
If a synonym is used in a trial creation accession list, it gives an error that the accession name is not in the database while validating the trial design. An example is the use of NASE3 in cassavabase.

For Bugs:
---------

**Comment by nickmorales** [comment] 2018-09-24 17:59
seems to work fine https://yambase.org/breeders/trial/1?format= ?

**Comment by lukasmueller** [comment] 2023-03-14 18:47
Duplicate of #4138 and #2216

**Closed by lukasmueller** 2023-03-14 18:47 UTC
