### ISSUE TITLE
New Trial Design Request: Wescott Design

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#1441] opened 2017-11-09 15:49 UTC
Expected Behavior 
--------------------------------------------------------------------------

The NaCRRI sweetpotato breeding group has asked for support for Wescott Design. They've suggested we contact the CIP stats team for design details, as it is already implemented in [HIDAP](https://research.cip.cgiar.org/gtdms/hidap/)

For Bugs:
---------

**Comment by bauchetg** [comment] 2018-03-15 18:08
duplicate of #1713

**Closed by bauchetg** 2018-03-15 18:08 UTC
