### ISSUE TITLE
Trial design fails, but creates an empty trial

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#3291] opened 2021-01-22 17:23 UTC
If an error occurs at the end of trial design due to in-valid accessions being in the list an empty trial is created, which has to be deleted before re-designing. It would be ideal if no trial was created on failure. Using Docker v18.

**Comment by lukasmueller** [comment] 2021-01-25 16:50
Hi Chris, I think we need more information on this ticket, maybe we can have a brief zoom call? Thanks!

**Comment by ch728** [comment] 2021-02-04 16:14
Hi Lukas, sorry for the delay. I have been troubleshooting trial design issues with our field technicians. This problem is directly related to https://github.com/solgenomics/sgn/issues/3282. The technician will copy and paste the accessions for the planting spreadsheet directly into a breedbase list and validate. The list passes validation because the validation is case insensitive. Then they will use this list in trial design which doesn't thrown and error to the very last step, which I'm guessing is case sensitive. The result is an error message and a blank trial is created. It's not a huge deal, we just delete the blank trial and I remind them that the case needs to be all uppercase, but it would be less confusing if all tools in BreedBase treated case in the same way.

**Comment by lukasmueller** [comment] 2021-02-04 19:40
We should probably match always case insensitively, except when adding new accessions...
________________________________

**Comment by ch728** [comment] 2021-02-04 20:22
yeah, that seems like it would be good, and if new accessions case insensitive match an existing accession it should be error I think. Nobody should be able to add Cypress as new accession if CYPRESS or cypress exist is in the database. I can't think of a scenario where that wouldn't be an accident.

**Comment by lukasmueller** [comment] 2021-02-11 17:57
Apparently there are some breeding programs that specify certain features of the accession using case. So for these programs, we should allow upload of new accession that match a current accession case insensitively.

**Comment by lukasmueller** [comment] 2021-04-01 23:41
In essence, this is a duplicate of #3397, and I will close this ticket.

**Closed by lukasmueller** 2021-04-01 23:41 UTC
Labels: Priority: High
