### ISSUE TITLE
user role UI on musabase is down

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1870] opened 2018-05-14 08:10 UTC
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------
https://musabase.org/breeders/manage_roles/
Access to "Manage" -> "User roles" page is down and throw and error related to server.pm
[error] Caught exception in engine "Wide character in syswrite at /usr/local/share/website/local-lib/lib/perl5/Starman/Server.pm line 553."

**Comment by nickmorales** [comment] 2018-05-14 16:27
A special character in a username is breaking the page

**Comment by lukasmueller** [comment] 2018-05-23 19:15
This can be fixed by changing the encoding of the file that the server writes to with utf8 encoding.
I'll make the change.

**Comment by nickmorales** [comment] 2018-09-06 20:19
username with special character was a fake account and was removed, so the issue is closed. not sure which special character was causing it to break

**Closed by nickmorales** 2018-09-06 20:19 UTC
Labels: Priority: Critical, Type: Bug

**Comment by nmenda** [comment] 2018-10-01 20:18
in SGN some accounts with special characters seem legit
