### ISSUE TITLE
Accession name case-insensitive?

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#3282] opened 2021-01-15 19:02 UTC
We have the accessions "CYPRESS", "JUPITER", and "ORION" in our database. When "Cypress", "Jupiter", and "Orion" are added to a list, fuzzy match says they are an exact uniquename match, and the list passes validation. However, if that same accession list is used to design a trial the trial design tool fails on the last confirmation step and says "Cypress", "Jupiter" and "Orion" don't exist in the database. My two cents is that the database should enforce case-sensitivity; case-insensitivity is convenient, but I think it enables the user to be careless . We are using v18 docker image.

**Comment by nickmorales** [comment] 2021-01-15 19:31
I definitely agree and have avoided changing the case-sensitivity

**Comment by lukasmueller** [comment] 2021-01-20 18:12
The basic philosophy that should be implemented in the database is the following: There can only be one entry in the database for any mixture of case. It should not allow to add accessions "Cypress" and "CYPRESS". That will lead to confusion. Once you have entered it as "Cypress" however, you should be careful to always refer to it by exactly that string. (Maybe Naama can comment who implemented this policy recently).

**Comment by nmenda** [comment] 2021-01-21 16:25
@lukasmueller @ch728 @nickmorales 
stock names should always be case insensitive. 
We need to fix the trial upload and make sure it matches stock names accordingly.

**Comment by lukasmueller** [comment] 2021-04-01 23:43
Duplicate of #3397

**Closed** 2021-04-01 23:44 UTC
