### ISSUE TITLE
Merging feature page into locus page

### ISSUE THREAD

**Issue by phosmani** [solgenomics/sgn#1100] opened 2017-06-21 15:45 UTC
Integrate Feature page information complementary to locus page (mRNA sequence, Genomic sequence and Related features).
Add computation prediction along with user curated function
Remove link to genome features on SGN.

**Comment by lukasmueller** [comment] 2017-10-31 16:20
I think it would be a good idea to have the protein, cds and mRNA sequence listed on the locus page, with a link to the feature page (to not overload the locus page)

**Comment by lukasmueller** [comment] 2017-10-31 16:22
Closed because it is a duplicate of #1399

**Closed by lukasmueller** 2017-10-31 16:22 UTC
Labels: solgenomics.net
