### ISSUE TITLE
list and dataset detail pages

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#2149] opened 2018-09-07 10:50 UTC
Wondering if it may be easier to view and cross-reference contents of lists and datasets to tools that can use their contents, and display related data??

**Comment by lukasmueller** [comment] 2018-09-24 18:17
Maybe give the number of elements in a list in the html selects?

**Comment by lukasmueller** [comment] 2019-04-22 15:36
Needs more clarification?

**Comment by lukasmueller** [comment] 2022-09-20 18:46
duplicate of #4116 .

**Closed by lukasmueller** 2022-09-20 18:46 UTC
