### ISSUE TITLE
Trial deletion: on trial details page, "Delete trial data" -> "Delete trait" data is not functionnal

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#512] opened 2016-05-31 17:09 UTC
Error message:
"An error occurred"

As well:
while clicking "Delete layout data", error message display while  "Delete trial data" has not been previously executed is "An error occurred: {UNKNOWN}: cannot delete because of associated phenotypes at lib/CXGN/Trial.pm line 697"
I could be more explicit, indicating the user has to perform  "Delete trial data" first

**Comment by lukasmueller** [comment] 2016-06-01 15:29
Enforce order of deletion on the user interface (activate links to delete layout only when traits are already deleted etc).

**Comment by lukasmueller** [comment] 2016-07-06 15:08
fixed via 66ba8dd85a18e1b3b71ba56c5f586121eff6f92d.

**Comment by bauchetg** [comment] 2016-07-18 16:19
Some confusing messages are obtained while deleting completely a trial:
After completing:  "Delete trait data" and "Delete layout data", deleting the trial was not successful for several trial tested with the message:  "Cannot delete entry because of associated experiment". This message is not very informative as it doesnt point which metadata remains to be deleted

Finally repeating the action after refreshing the trial page,  "Delete trial entry" gave first the following message:
 "An error occurred: {UNKNOWN}: Can't call method "name" on an undefined value at lib/CXGN/Trial.pm line 936. at lib/CXGN/Trial.pm line 731" (This refer to line:  my $phenome_schema = shift;)
Afterwards, a message confirming the trial deletion was displayed.

It seems that the trial layout deletion is not always effective at first.

**Comment by lukasmueller** [comment] 2016-08-31 20:55
Yes, trial deletion can take a long time... It should probably display a working... window if it isn't already.

**Comment by lukasmueller** [comment] 2016-09-07 16:03
Duplicate of #552. Closing.

**Closed by lukasmueller** 2016-09-07 16:03 UTC
