### ISSUE TITLE
search wizard: genotype download by trial

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#774] opened 2016-12-07 11:26 UTC
--like phenotype download by trial

**Comment by bellerbrock** [comment] 2016-12-07 23:11
Hey Isaak, 

Is this an idea for a new feature, or a refinement of the current genotype download? 
Right now users can select a trial in one of the first panels, then select it's accessions and a genotyping protocol in the next panels before hitting 'Download Genotypes'.

**Comment by isaak** [comment] 2016-12-08 15:17
it is more a convenience option (a step shorter than having to selection all accession for users who download the genotype data of all accessions in a trial) and consistent with the phenotype download option (which allows by trial).

**Comment by bellerbrock** [comment] 2016-12-08 15:30
Ok, makes sense. They will have to chose a genotyping protocol too, but if not we could set a default

**Comment by isaak** [comment] 2016-12-08 15:33
Yes. And also if you want to use a default protocol, it is set in the sgn_local.conf

**Comment by nickmorales** [comment] 2017-01-11 15:58
need to fix duplicate of genotype issue in fixture

**Closed** 2017-01-11 17:43 UTC
