### ISSUE TITLE
Selection index error

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1057] opened 2017-06-08 15:36 UTC
Error while retrieving trial data, here is the log:
QUERY: SELECT table0.accession_id, table0.accession_name,  ROUND( CAST(table1.trait1 AS NUMERIC), 2),  ROUND( CAST(table2.trait2 AS NUMERIC), 2) FROM (SELECT accession_id, accession_name FROM materialized_phenoview WHERE trial_id = 443 GROUP BY 1,2) AS table0 JOIN (SELECT accession_id, accession_name, AVG(phenotype_value::REAL) AS trait1 FROM materialized_phenoview WHERE trial_id = 443 AND trait_id = ? GROUP BY 1,2) AS table1 USING (accession_id) JOIN (SELECT accession_id, accession_name, AVG(phenotype_value::REAL) AS trait2 FROM materialized_phenoview WHERE trial_id = 443 AND trait_id = ? GROUP BY 1,2) AS table2 USING (accession_id) ORDER BY 2
DBD::Pg::st execute failed: ERROR:  column "accession_name" does not exist
LINE 1: ...trait2 AS NUMERIC), 2) FROM (SELECT accession_id, accession_...
                                                             ^ at lib/CXGN/BreederSearch.pm line 197.
[error] Caught exception in SGN::Controller::AJAX::BreederSearch->get_avg_phenotypes "DBD::Pg::st execute failed: ERROR:  column "accession_name" does not exist
LINE 1: ...trait2 AS NUMERIC), 2) FROM (SELECT accession_id, accession_...
                                                             ^ at lib/CXGN/BreederSearch.pm line 197."

**Comment by bellerbrock** [comment] 2017-06-08 15:46
Hi Guillaume, this problem is caused by the update to the materialized views. It's fixed in a branch with this commit: 4015ace79bbb6e5680a7de140d3df4e113d8abc7 , but the branch isn't ready to merge yet.

There's no reason to wait though, I'll make a branch specific to this, cherry pick the commit, then we can merge just the fix

**Closed** 2017-06-08 18:10 UTC
