### ISSUE TITLE
special characters in sgn user names 

### ISSUE THREAD

**Issue by nmenda** [solgenomics/sgn#2196] opened 2018-09-28 20:33 UTC
Expected Behavior 
--------------------------------------------------------------------------

causing manage_roles to crash 

For Bugs:
---------

**Comment by bauchetg** [comment] 2018-09-28 20:35
Duplicate of #1678

**Comment by nmenda** [comment] 2018-10-04 22:02
#2203

**Comment by nmenda** [comment] 2018-10-04 22:03
duplicate of 
https://github.com/solgenomics/sgn/issues/2195

**Closed** 2018-10-05 17:40 UTC
Labels: www: solgenomics.net
