### ISSUE TITLE
Calendar use case for project pre-planning.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#1846] opened 2018-04-20 14:06 UTC
Expected Behavior 
--------------------------------------------------------------------------
Breeders would want to preplan for a project to be added to the database, and also be able to track its implementation as the different activities are carried out.

This has been requested by Ted's group. They basically want to plan a project and follow each of those activities during implementation. They would want to add an event for field preparation, planting, phenotyping and harvesting. As well as every other activity in between planting and harvesting. 

For Bugs:
---------

**Comment by bauchetg** [comment] 2018-04-20 14:53
see other issues in the calendar/trial activity project

**Comment by lukasmueller** [comment] 2021-10-10 15:37
Duplicate of #876

**Closed** 2021-10-10 15:37 UTC
