### ISSUE TITLE
upload field book database.csv file from brAPI

### ISSUE THREAD

**Issue by lynnjo** [solgenomics/sgn#3829] opened 2021-11-18 19:36 UTC
Expected Behavior 
--------------------------------------------------------------------------

On our android devices with the FieldBook app: We upload a trial from breedbase using brAPI.  Then record phenotype trait values, then download to breedbase from Fieldbook (which goes back through brAPI.  This works fine when the network/server/db are all available.  

When we are unable to download to breedbase, we export the files from field book to be loaded later.  When trying to load these saved exported Fieldbook  *database.csv files  via the GUI "Manage-> Phenotypes -> Upload Fieldbook Database File" we get the error:

“File contents incorrect. First column in header is Row, but it must be plot_id, plot_name, plant_name, or subplot_name.” which appears to come from CXGN::Phenotypes::ParseUpload::Plugin::FieldBook.pm

We'd like for the breedbase code to accept and parse the headers/columns when the field was loaded via brAPI, as brAPI is a supported interface to breedbase.

I've attached an example file. (I think - I dragged something

For Bugs:
---------

#### Steps to Reproduce

<!-- this bug. Include code to reproduce, if relevant.               --

Load file from Breedbase GUI with headers as shown in the file below: Manage-> Phenotypes -> Upload Fieldbook Database File

[2021-10-08-04-52-20_A21NYHC_StandCount_database.csv](https://github.com/solgenomics/sgn/files/7565519/2021-10-08-04-52-20_A21NYHC_StandCount_database.csv)

>

**Comment by lynnjo** [comment] 2021-11-18 19:37
I dragged a file, but don't see it.  The relevant information is the header line from the file, which looks like:

"Row","Column","Entry","Plot","Plant","Germplasm","observationUnitDbId","observationUnitName","trait","value","timestamp","person","location","number"

**Comment by lukasmueller** [comment] 2021-11-20 13:34
Hi Lynn, so you are loading the fieldbook using BrAPI, then you export to a file (Fieldbook Database format?) and you upload that using the file upload function? I agree that this should be possible. Could you try again to attach the file, it would be helpful.

**Comment by lukasmueller** [comment] 2021-11-21 03:55
Hi Lynn, this issue may be a duplicate of #3820. In that issue, the file uploaded seems to have DOS-style line endings which is unexpected, as it usually comes from an Android (Linux) device. 
I created a patch to remove \r characters from the file on upload. This may also fix this issue.

**Comment by lynnjo** [comment] 2021-11-22 11:42
Hi Lukas - I saw 3820, but assumed this was different because in my case, the code sees the header line, it just doesn't like the values it encounters.  From the error message:

First column in header is Row, but it must be plot_id, plot_name, plant_name, or subplot_name.

The field was loaded from brAPI so the export has the same header columns in the same order that brAPI supplied, which is:

"Row","Column","Entry","Plot","Plant","Germplasm","observationUnitDbId","observationUnitName","trait","value","timestamp","person","location","number" .

I think breedbase should accept a header that has columns ordered by brAPI.  I'll try uploading the file again, and if it doesn't work I'll send to you in Slack.
[2021-10-08-02-20-17_A21NYH2_StandCount_database.csv](https://github.com/solgenomics/sgn/files/7580681/2021-10-08-02-20-17_A21NYH2_StandCount_database.csv)

**Comment by lukasmueller** [comment] 2021-11-23 18:28
I am not quite clear - re-ordering the headers worked? If not we should definitely try to have the other order accepted as well. One should not have to re-order it manually :-)

**Comment by lynnjo** [comment] 2021-11-23 19:58
I programmatically created an xls spreadsheet in the "SImple" format using
the Fieldbook database.csv file as input.  But we'd prefer not to have to
do that - would like to be able to upload the stored Fieldbook file.

**Comment by chris263** [comment] 2023-10-13 15:13
I guess this one can be closed. Right?

**Comment by lynnjo** [comment] 2023-10-13 15:19
Was functionality added that accepts the BrAPI ordering of the columns?  

If not, I'd like to keep it open.  While the workaround does get the data loaded, I thought supporting the import of BrAPI files was a goal of BreedBase functionality.  Perhaps not a high priority, but somewhere on the list?

**Closed** 2023-10-30 16:14 UTC
Labels: Priority: Critical, Type: Bug
