### ISSUE TITLE
Field Layout: Transpose Does Not Update

### ISSUE THREAD

**Issue by dwaring87** [solgenomics/sgn#4150] opened 2022-06-27 12:53 UTC
Expected Behavior 
--------------------------------------------------------------------------

When using the Transpose button on the Field Layout display, the layout is not updated after submitting the changes.

The materialized_phenotype_jsonb_table needs to be manually refreshed in order for the changes to appear.

For Bugs:
---------

**Comment by lukasmueller** [comment] 2022-06-30 15:20
Duplicate of the BrAPI issue

**Closed** 2022-06-30 15:25 UTC
