### ISSUE TITLE
cannot refresh materialized_stockprops

### ISSUE THREAD

**Issue by nmenda** [solgenomics/sgn#3273] opened 2021-01-13 22:02 UTC
Expected Behavior 
--------------------------------------------------------------------------
Error: field name must not be null

happens only in cxgn_cassava  and sandbox_cassava 

For Bugs:
---------

**Comment by bellerbrock** [comment] 2021-01-14 00:05
Caused by empty strings in stock uniquenames and stockprop values. I fixed the problem stocks and props in cxgn_cassava, but we need a code and/or table defintion update to better enforce a 'no empty strings' rule for user input.

**Comment by lukasmueller** [comment] 2021-01-21 16:25
Change Stock object to not allow empty strings as names.

**Comment by bellerbrock** [comment] 2021-02-18 15:59
Turns out the Stock object [already enforces this](https://github.com/solgenomics/sgn/blob/master/lib/CXGN/Stock.pm#L308).  Editing an existing stock's name to an empty string fails with error `Attribute (name) does not pass the type constraint because: Validation failed for 'Str' with value undef at accessor CXGN::Stock::name (defined at /home/production/cxgn/sgn/bin/../lib/CXGN/Stock.pm line 321) `
Adding a new stock with name as empty string fails even early because of list and file parsing checks. So no idea how the empty strings stocks got into Cassavabase, but it must not have been through the user interface. Closing this one now!

**Closed by bellerbrock** 2021-02-18 15:59 UTC
Labels: Priority: Critical
