### ISSUE TITLE
common login to all breedbases

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#4305] opened 2022-11-24 05:38 UTC
Expected Behavior 
--------------------------------------------------------------------------

A participant in the breedbase workshop (ISTRC) asked if they could login with the same account, created in one of the DBs, to the other DBs.

For Bugs:
---------

**Comment by lukasmueller** [comment] 2022-12-07 22:25
duplicate of #2323.

**Closed** 2022-12-07 22:25 UTC
