### ISSUE TITLE
Enhance Genotype Search Obj

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#1518] opened 2017-12-19 21:30 UTC
Expected Behavior 
--------------------------------------------------------------------------
 Add functions to retrieve genotypes by specific alleles, retrieve specific ranges, etc. 

For Bugs:
---------

**Comment by lukasmueller** [comment] 2020-11-20 15:32
Duplicate of #1847.

**Closed** 2020-11-20 15:32 UTC
