### ISSUE TITLE
Mechanism for suppressing further data from a plot

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#1361] opened 2017-10-12 20:17 UTC
Expected Behavior 
--------------------------------------------------------------------------
A QC suggestion from yesterday's discussion with Josh from IRRI. Sometimes, partway through a trial a breeder will realize the need to throw out any further data from a plot (or other experimental unit) due to realities in the field such as animal damage. 
Deletion doesn't solve this because not all data needs to be thrown out, and it can be useful to track when data is suppressed vs. actually absent. We discussed the possibility of using a timestamp to indicate time of suppression, and perhaps fields for operator and reason. Then allow for further measurements to be made on the plot but exclude data collected after suppression from most analyses.

For Bugs:
---------

**Comment by lukasmueller** [comment] 2017-10-18 19:18
1) store the information about "bad plots" with timestamp as a sort of trait and then allow people to exclude these plots from analysis
2) Use field map to show traits and allow clicking on plots to exclude them from analysis

**Comment by bauchetg** [comment] 2018-03-03 07:17
Having the a plant/plot status column in the fieldbook layout could give user access to this information and/or giva ability to update on plot/plant status. Current limitation of fieldbook are in its "Next entry with no data" and "Hide entries with data" which are made for unique traits and not for the whole traits set based on a possible plant/plot status

**Comment by aco46** [comment] 2018-03-04 08:27
@bauchetg : The field map tracks plots with plants. On mouseover, if a plot has plant, it shows you the number of plant in that plot. If I understand correctly, could this be the use case for the above feedback?

The assignment of inactive status to a plot, can easily be captured in the fieldbook. And it's best within the fieldbook during phenotyping. If a plot has no phenotype for any assayed trait, it is shown on the trait-heatmap.

**Comment by bauchetg** [comment] 2020-07-29 21:25
duplicate of #3017

**Closed by bauchetg** 2020-07-29 21:25 UTC
