### ISSUE TITLE
Outlier handling in GS and other analyses

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#418] opened 2016-02-22 19:01 UTC
http://link.springer.com.proxy.library.cornell.edu/article/10.1007/s00122-016-2666-6

Suggested for implementation in cassavabase for all analyses  by Jean-Luc. 

(I will implement it on GS, correlation analyses...)

**Comment by lukasmueller** [comment] 2023-01-12 16:10
Duplicate of #3800

**Closed by lukasmueller** 2023-01-12 16:10 UTC
Labels: Type: Feature Request, Priority: Normal
