### ISSUE TITLE
Additional use case to Calendar tool.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#1695] opened 2018-03-09 14:03 UTC
Expected Behavior 
--------------------------------------------------------------------------
Breeders would want an optional ability for the Calendar tool to directly display the harvest date of a trial when given the number of days a trial would be in the field.

For Bugs:
---------

**Comment by bauchetg** [comment] 2018-03-10 09:34
@aco46 this is a duplicate of #876 where harvest date is one of the requested props

**Closed by bauchetg** 2018-03-10 09:34 UTC

**Comment by aco46** [comment] 2018-03-10 11:05
@bauchetg thanks.
