### ISSUE TITLE
images stored in cassavabase are not linked to stock synonyms

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#709] opened 2016-10-12 23:42 UTC
In "search", "image"  searching for W940245, five images are in the output. Search for its synonym IITA-TMS-WAR940245 has no data.

**Comment by lukasmueller** [comment] 2023-03-13 14:56
duplicate of #2116 . Closing this one.

**Closed by lukasmueller** 2023-03-13 14:56 UTC
Labels: Type: Implementation, Priority: Normal
