### ISSUE TITLE
Would it be possible to have control/checks as an additional search criteria in the wizard? 

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#1697] opened 2018-03-09 14:21 UTC
Expected Behavior 
--------------------------------------------------------------------------
Breeders would want an additional option of retrieving accessions or plots used as controls/checks in trials from the wizard. 

For Bugs:
---------

**Comment by bauchetg** [comment] 2018-03-10 09:30
see: #1470

**Comment by lukasmueller** [comment] 2021-10-10 02:39
Duplicate of #1470, closing.

**Closed by lukasmueller** 2021-10-10 02:39 UTC
