### ISSUE TITLE
trial deletion is not deleting plots

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#4525] opened 2023-05-04 11:19 UTC
Expected Behavior 
--------------------------------------------------------------------------

Trial deletion from the trial detail page is not deleting associated plots. (Prasad).

For Bugs:
---------

**Comment by lukasmueller** [comment] 2023-05-16 13:27
In the test database, the deletion works. What was the trial id of the reported trial? I can then check the deletion process of that trial in an old database dump.

**Comment by isaak** [comment] 2023-05-16 13:29
@pvnsprasad may remember...

**Comment by lukasmueller** [comment] 2023-09-06 09:41
Could not reproduce... closing this issue for now, re-open if it re-occurs.

**Closed by lukasmueller** 2023-09-06 09:41 UTC
Labels: Priority: Critical, Type: Bug
