### ISSUE TITLE
breedBase database

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#2575] opened 2019-08-09 10:19 UTC
-- For demo purposes (speed), using the fixture db would be good.

**Comment by lukasmueller** [comment] 2019-10-21 15:13
We have a site called breedbase.org that can serve as a demo site. Is that what you were thinking?

**Comment by isaak** [comment] 2019-10-21 16:06
Yes, but use a light database (like the fixure db) instead of a copy of production db.

**Comment by lukasmueller** [comment] 2019-10-28 21:31
I can put a copy of the fixture there instead.

**Comment by lukasmueller** [comment] 2019-11-18 16:18
Confirmed in ticket meeting: put fixture on Breedbase

**Comment by lukasmueller** [comment] 2023-03-14 18:34
duplicate of #4306

**Closed** 2023-03-14 18:42 UTC
